### ISSUE TITLE
User Story: Create an account

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#1]
As a **new user** I can **register for the website** so that **I can hold an account**

## Approval Criteria
- User can create an account

## Tasks
- [x] Set up allauth
- [x] Create a signup page
- [x] Style the UI
