### ISSUE TITLE
User Story: Add to bag

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#16]
As a **user** I want **a shopping bag** so that **I can add products to it**

## Approval Criteria
- User can add a product to the shopping bag

## Tasks
- [x] Create the bag app
- [x] Create the view
- [x] Create the template
