### ISSUE TITLE
User Story: Checkout securely

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#20]
As a **user** I want **to be able to checkout and get feedback** so that **I can buy things.**

## Approval Criteria
- Checkout works 
- User gets feedback email
- User gets on site feedback

## Tasks
- [x] Add checkout app
- [x] Integrate Stripe
- [x] Create messages on site
- [x] Wire up email response
