### ISSUE TITLE
User Story: Blog post view

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#21]
As a **user** I want **a page that displays blog posts** so that **I can read them**

## Approval Criteria
- Page lists all blog posts

## Tasks
- [x] Create an app for blog
- [x] Create a view for view posts 
- [x] Create a model for this
- [x] Create a template to render the posts to
