### ISSUE TITLE
User Story: Landing page

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#32]
As a **user** I want **an intuitive landing page** so that **I know where I am without having to ask**

## Approval Criteria
- Good UI

## Tasks
- [x] Build hero section
- [x] Add ad sections
- [x] Product branding 
- [x] Logos visible
- [x] Add HTML template
