### ISSUE TITLE
Product admin

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#36]
As a **admin** I want **edit,delete and upload form** so that **I can manage products**

## Approval Criteria
- Can add
- Edit
- and delete products without logging into Django admin

## Tasks
- [x] Create an edit page 
- [x] Create a delete button
- [x] Create an upload page

**Comment by mmcin** [comment]
-
