### ISSUE TITLE
User Story: Browse products

### ISSUE THREAD

**Issue by mmcin** [martin-mcinerney/CI-PP5#5]
As a **user** I want **a product page** so that **I can browse available products**

## Approval Criteria
- Product page
- Products can be viewed 

## Tasks
- [x] Add DB model for products
- [x] Build and Style product page
- [x] Add products to DB
- [x] Add view 
- [x] Add url
